### ISSUE TITLE
Crash in certain biomes

### ISSUE THREAD

**Issue by MCEventHorizon** [sekelsta/horse-colors#37]
Hello, I've been searching why I was crashing in certain biomes and I think it's your mod that's causing the issue.
![Screenshot_3](https://user-images.githubusercontent.com/15619786/127190564-480c044e-efd5-4b66-94f3-3d2ea3f71944.png)
I saw this issue on this post and I think it's the same as this one, I think it's an incompatibility with Biomes O'Plenty cause some biomes probably have spawn weight of 0 and your mod is trying to spawn mobs. I removed your mod and everything is working on the same seed so I think this is the issue.

Crash report:
---- Minecraft Crash Report ----
// Hey, that tickles! Hehehe!

Time: 7/27/21 6:02 PM
Description: Exception generating new chunk

java.lang.IllegalArgumentException: null
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:20) ~[?:?] {re:classloading}
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:39) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:334) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.run(SourceFile:105) ~[?:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:1.8.0_301] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:20) ~[?:?] {re:classloading}
	at net.minecraft.util.WeightedRandom.func_76271_a(SourceFile:39) ~[?:?] {re:classloading}
	at net.minecraft.world.spawner.WorldEntitySpawner.func_77191_a(WorldEntitySpawner.java:334) ~[?:?] {re:classloading}
	at net.minecraft.world.gen.NoiseChunkGenerator.func_230354_a_(NoiseChunkGenerator.java:623) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_222602_b(ChunkStatus.java:89) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.chunk.ChunkStatus$ISelectiveWorker.doWork(ChunkStatus.java:240) ~[?:?] {re:classloading}
	at net.minecraft.world.chunk.ChunkStatus.func_223198_a(ChunkStatus.java:198) ~[?:?] {re:classloading,pl:accesstransformer:B}
-- Chunk to be generated --
Details:
	Location: -138,-77
	Position hash: -326417514634
	Generator: net.minecraft.world.gen.NoiseChunkGenerator@22caa6f
Stacktrace:
	at net.minecraft.world.server.ChunkManager.lambda$null$18(ChunkManager.java:524) ~[?:?] {re:classloading}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.0.26.jar:?] {re:classloading,re:classloading,re:classloading}
	at net.minecraft.world.server.ChunkManager.lambda$scheduleChunkGeneration$20(ChunkManager.java:522) ~[?:?] {re:classloading}
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source) ~[?:1.8.0_301] {}
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:1.8.0_301] {}
	at net.minecraft.world.chunk.ChunkTaskPriorityQueueSorter.func_219083_b(SourceFile:58) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213148_e(SourceFile:94) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.DelegatedTaskExecutor.func_213145_a(SourceFile:137) ~[?:?] {re:classloading}

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['EventHorizon_'/271, l='ServerLevel[New World]', x=-2129.67, y=105.11, z=-1256.17]]
	Chunk stats: ServerChunkCache: 2979
	Level dimension: minecraft:overworld
	Level spawn location: World: (-152,63,-134), Chunk: (at 8,3,10 in -10,-9; contains blocks -160,0,-144 to -145,255,-129), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 2200 game time, 2200 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 64947 (now: false), thunder time: 80511 (now: false)
	Known server brands: forge
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:854) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:78) ~[?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?] {re:classloading,pl:accesstransformer:B}
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_301] {}

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_301, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 3868106184 bytes (3688 MB) / 8589934592 bytes (8192 MB) up to 8589934592 bytes (8192 MB)
	CPUs: 6
	JVM Flags: 13 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx6144m -Xms256m -XX:PermSize=256m -XX:+UseG1GC -Xmx8G -Xms8G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.2.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.5-36.2.0.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.2.jar mixin TRANSFORMATIONSERVICE 
		/forge-1.16.5-36.2.0.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.0
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.0-client.jar                    |Minecraft                     |minecraft                     |1.16.5              |DONE      |Manifest: NOSIGNATURE
		astikorcarts-1.16.5-1.1.1.jar                     |AstikorCarts                  |astikorcarts                  |1.1.1               |DONE      |Manifest: NOSIGNATURE
		forge-1.16.5-36.2.0-universal.jar                 |Forge                         |forge                         |36.2.0              |DONE      |Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		horse_tack-3.0-1.16.3release.jar                  |Horse Tack                    |horse_tack                    |3.0                 |DONE      |Manifest: NOSIGNATURE
		BiomesOPlenty-1.16.5-13.1.0.477-universal.jar     |Biomes O' Plenty              |biomesoplenty                 |1.16.5-13.1.0.477   |DONE      |Manifest: NOSIGNATURE
		MrCrayfishs-Furniture-Mod-1.16.5.jar              |MrCrayfish's Furniture Mod    |cfm                           |7.0.0-pre19         |DONE      |Manifest: NOSIGNATURE
		horse_colors-1.16.5-1.6.0.2.jar                   |Realistic Horse Genetics      |horse_colors                  |1.16.5-1.6.0.2      |DONE      |Manifest: NOSIGNATURE
	Crash Report UUID: 4e6f80fe-1fbf-487d-b696-2e3b89f79281
	Player Count: 1 / 8; [ServerPlayerEntity['EventHorizon_'/271, l='ServerLevel[New World]', x=-2129.67, y=105.11, z=-1256.17]]
	Data Packs: vanilla, mod:astikorcarts, mod:forge, mod:horse_tack (incompatible), mod:biomesoplenty, mod:cfm (incompatible), mod:horse_colors
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'forge'

**Comment by sekelsta** [comment]
Thanks for the report! I haven't been able to reproduce this crash yet. If you could get me the world seed, that would be super helpful.

**Comment by MCEventHorizon** [comment]
Just download BiomesOPlenty and add 2 of your mods, I uploaded a video where you can see everything: https://youtu.be/HeQ5aEJg_f4

**Comment by sekelsta** [comment]
Thanks! It seems this issue is caused by setting `horseSpawnMultiplier` in the config to values smaller than 1.0. I'll have a fix soon, but in the meantime if you set that value back to 1.0 or higher it should fix the crashes.

**Comment by MCEventHorizon** [comment]
Oh, I get it. So how would I disable them spawning in the wild then?

**Comment by sekelsta** [comment]
It's fixed in the code now and once the next update it out will no longer crash even with horseSpawnMulitplier set to 0.

Record for posterity: the crash was with a seed 'Test', after teleporting to coordinates 3440, 120, -3160 with horseSpawnMultiplier set to 0.0 and with these mods installed:
astikorcarts-1.16.5-1.1.1.jar
BiomesOPlenty-1.16.5-13.1.0.477-universal.jar
cfm-7.0.0-pre19-mc1.16.3.jar
horse_colors-1.16.5-1.6.1.1.jar
horse_tack-3.0-1.16.3release.jar
